version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - budget-service
      - bills-service
      - investment-service
      - education-service
    environment:
      - NODE_ENV=development
      - PORT=8000

  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - MONGO_URI=mongodb://mongo:27017/stratos-users
    depends_on:
      - mongo

  account-service:
    build: ./services/account-service
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - PORT=8002
      - MONGO_URI=mongodb://mongo:27017/stratos-accounts
    depends_on:
      - mongo

  transaction-service:
    build: ./services/transaction-service
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
      - PORT=8003
      - MONGO_URI=mongodb://mongo:27017/stratos-transactions
    depends_on:
      - mongo

  budget-service:
    build: ./services/budget-service
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
      - PORT=8004
      - MONGO_URI=mongodb://mongo:27017/stratos-budgets
    depends_on:
      - mongo

  bills-service:
    build: ./services/bills-service
    ports:
      - "8005:8005"
    environment:
      - NODE_ENV=development
      - PORT=8005
      - MONGO_URI=mongodb://mongo:27017/stratos-bills
    depends_on:
      - mongo

  investment-service:
    build: ./services/investment-service
    ports:
      - "8006:8006"
    environment:
      - NODE_ENV=development
      - PORT=8006
      - MONGO_URI=mongodb://mongo:27017/stratos-investments
    depends_on:
      - mongo

  education-service:
    build: ./services/education-service
    ports:
      - "8007:8007"
    environment:
      - NODE_ENV=development
      - PORT=8007
      - MONGO_URI=mongodb://mongo:27017/stratos-education
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: