services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
    environment:
      - PORT=8000
      - USER_SERVICE_URL=http://user-service:8001
      - COMMUNITY_SERVICE_URL=http://community-service:8002
    networks:
      - stratos-network

  # User Service
  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    depends_on:
      - user-db
    environment:
      - PORT=8001
      - MONGODB_URI=mongodb://user-db:27017/stratos-users
      - JWT_SECRET=your_jwt_secret_here
    networks:
      - stratos-network

  # Community Service
  community-service:
    build: ./services/community-service
    ports:
      - "8002:8002"
    depends_on:
      - community-db
    environment:
      - PORT=8002
      - MONGODB_URI=mongodb://community-db:27017/stratos-community
      - JWT_SECRET=your_jwt_secret_here
    networks:
      - stratos-network


  # Databases for each service
  user-db:
    image: mongo:latest
    volumes:
      - user-data:/data/db
    networks:
      - stratos-network


  # Add community database
  community-db:
    image: mongo:latest
    volumes:
      - community-data:/data/db
    networks:
      - stratos-network

volumes:
  user-data:
  community-data:

networks:
  stratos-network:
    driver: bridge